# ASP.NET Core
# Build and ftest ASP.NET Core projects targeting .NET Xore.
# Add steps fthat run ftests, createa NuGet package, deploy, and more:
# https : //docs. mic rosoft.com/azu re/devops/pipelines/languages/dotnet-co re

trigger:
— main

pool:
    vmlmage: ubuntu—latest

variables:
    buildConfiguration: ' Release '

steps:
— script: dotnet build —configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'